# -*- coding: UTF-8 -*-
testList = ["aaa", "bbb", "ccc", "ddd", "eee", "fff"]
print(testList)
del testList[2]
print(testList)
popValue = testList.pop(2)
print(testList)
print(popValue)
testList.append("agb")
print("========")
print(testList)
ga = testList.remove("eee")
print(testList)
print(ga)
print("========")
testList.__delitem__(1)
print(testList)
testList.insert(1, "test")
print(testList)

print("\n====sort 永久排序====\n")
sortList = ["gag", "sfd", "ad", "sd", "wf", "hr", "ld"]
sortList.sort()
print(sortList)
sortList.sort(reverse=True)
print(sortList)

print("\n====sorted 临时排序====\n")
sortedList = ["afd", "hdf", "ar", "sh", "jk", "we", "yr"]
print(sorted(sortedList, reverse=True))
print(sorted(sortedList, reverse=True)[1])
print(sortedList)
print("\n====reverse排序====\n")
reverseList = ["测试1", "测试2", "测试3", "测试4", "测试5", "测试6", 3, "sflsd"]
reverseList.reverse()
print(reverseList)
reverseList.reverse()
print(reverseList)
print(reverseList.__len__())
print(len(reverseList))
print(reverseList[-1])
print(reverseList[len(reverseList) - 1])

print("\n====遍历====\n")
for value in reverseList:
    print("item :" + str(value).title())

print("\n====区间====\n")
numberList1 = list(x ** 2 for x in range(2, 1000, 2) if x % 2 == 0)
print(min(numberList1))
print(max(numberList1))
print(sum(numberList1))
numberList2 = list(range(1, 10, 3))
print(numberList2)
numberList3 = list(x ** 2 for x in range(0, 20, 2) if x % 2 == 0)
print(numberList3)
numberList = list(x * y for x in numberList1 for y in numberList3)
print(numberList)
strList = list(x + y for x in "hu" for y in "di")
print(strList)
print("hd" in strList)
print("hd" not in strList)

print("\n====切片====\n")
print(strList[2:5])
print(strList[:10])
print(strList[2:])
print(strList[-2:])
print('==')
print(strList[:])
print(strList == strList[:])
